### ISSUE TITLE
Studio ORG filter

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#37]
Create search/login filter for organisations in Studio

**Comment by dominicfollett** [comment]
[Microsites Themeing](https://github.com/edx/edx-platform/wiki/Microsites-Theming) 

is an offering from Edx that allows you to (along with themeing) filter out courses that are not part of a particular Organisation. However the mechanism this relies on is by the use of a subdomain.

In this case, if we were to restrict the Bank of England to only it's courses, then we would have to have  `boe.learn.proversity.org` or similar, where `course_org_filter` in the microsite configuration would have to be set to Boe (note the uppercase). (plus other various configuration options)

**Comment by dominicfollett** [comment]
Create a separate table called `organizations_organizationuser` (similar to `organizations_organizationcourse`). 

It will look as follows:

``` text
+-----------------+--------------+------+-----+---------+----------------+
| Field           | Type         | Null | Key | Default | Extra          |
+-----------------+--------------+------+-----+---------+----------------+
| id              | int(11)      | NO   | PRI | NULL    | auto_increment |
| created         | datetime     | NO   |     | NULL    |                |
| modified        | datetime     | NO   |     | NULL    |                |
| user_id       | varchar(255) | NO   | MUL | NULL    |                |
| active          | tinyint(1)   | NO   |     | NULL    |                |
| organization_id | int(11)      | NO   | MUL | NULL    |                |
+-----------------+--------------+------+-----+---------+----------------+

```

Where `user_id` is the id in the `auth_user` table. A user may belong to only on organisation. A user is linked to the organisation in a similar fashion to the way a course is linked to an organisation in the admin backend. Filtering works by returning only those courses who ORG exists in the set of a user's ORGS.
In order for filtering to work correctly courses must be linked to organisations. If they are not, then any tenant should be able to view them (nice for demo courses).

If user not linked to organisation, then be able to see everything.

*\* Must be one to one, if a user adds a course, that course must be automatically linked to the organizational tag belonging to that user.

Nothing is applied to the lms.

Will need to:
1. Create a new model
2. Generate a migration
3. Add a method to the admin backend
4. Apply the filtering
5. Run some cms tests to see if there are major implication to this tenanting system.

**Comment by dominicfollett** [comment]
Edit: there is a `userortag` table existing already, although this might be geared toward Edx's Micosites tenancy support. I can't find an option in the admin backend to set this, and it might appear that is only supports one organisation.

**Comment by dominicfollett** [comment]
[How to delete a course in Edx](https://openedx.atlassian.net/wiki/display/PLAT/How+to+Delete+a+Course)

**Comment by dominicfollett** [comment]
To use this:
1. Make sure the migrations are performed
2. Make sure the `FEATURE['ORGANIZATIONS_APP'] = True` in envs/common.py
3. Make sure the course filtering Middleware is included in cms/envs/common.py `'student.middleware.UserCourseFilteringMiddleware',`
4. This should NEVER be included under lms envs.

**Comment by dominicfollett** [comment]
There are two failing tests in: `cms/djangoapps/contentstore/tests/test_contentstore.py`

--- `test_create_course_no_course_creators_not_staff`
--- `test_create_course_with_course_creator`

Both of these tests, have `ENABLE_CREATOR_GROUP` set to true.

Because of our issues with Course Creation on Staging, we have altered the method `_create_or_rerun_course` in `cms/djangoapps/contentstore/views/course.py` so that it no longer checks whether the user has the Role of a CourseCreator. Essentially this check should pass fine when ENABLE_CREATOR_GROUP is False,  however on staging,  even with this switched to False, this check fails, and permission is denied.  Perhaps something weird is going on and ENABLE_CREATOR_GROUP is actually True. We could completely dispel this worry if we check the setting directly in the above function, and if True throw a 403.

Some [info on Course Creation](https://github.com/edx/edx-platform/wiki/Controlling-course-creation-rights). This appears a bit outdated ...
