### ISSUE TITLE
Cannot save Free Text Response component when user adds a 'Full credit key phrases'

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#455]
When creating a new component 'Free Text Response' and the user want to add key word(s) or Phrase(s) he cannot save the the changes made. This also happens when the user select 'Half credit key phrases'

Steps to reproduce:

1. Click on the link below - it will take you the component Free text response
http://staging.studio.proversity.io/container/block-v1:PRO+QA-101+2017_QA01+type@vertical+block@7adb971faafa4252b0339f43faa03400?action=new
2. Click on edit
3. Scroll down until you find the sections 'full credit key or half credit key phrases'
4. Enter text in full credit key phrase box
5. Select save - nothing happens 
6. Delete the text and enter text in half key phrases section
7. Select save

Results:
When the user saves his changes of the key phrases nothing happens.
Their appear to be error messages in the console - See screenshot below.

Expected results:
When the use saves the changes it should save and window should close

![image](https://user-images.githubusercontent.com/31007393/30166715-68f08542-93e4-11e7-9d07-2a113f2bcd19.png)

**Comment by nicovanniekerk** [comment]
@mariushuman this is not a bug, well not like you think it is, the fields above are both json fiels, i.e. you will have to enter the text in the following syntax.
Correct:
   ["word1", "word 2"]
Incorrect:
  [word 1, word 2]

The actual bug here is that it does not present an error message, it just fails to save with no reason. Can you please re-log this ticket against the freetextresponse repo, stating this errors, but it must be enhanced to display the error to the user and not just fail with no messsage.

i.e. the error handling in the json of the freetextresponse xblock needs to be enhanced to show errors in a dialog box and not throw them away.

@renevatium @lidijarad FYI
