### ISSUE TITLE
Transcripts get overwritten when new ones are loaded

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#458]
When a user upload a transcript for a video, and uploads another one it over wrights the previous one that was loaded. This appear to only happen on TEA006 Online Movement Curriculum (Staff), Module 2 section

NOTE: Github does not support .srt 'upload file'
To get .srt files click on the link below and download the following srt files:
https://drive.google.com/drive/folders/0B2NmONYK4TdDbmVsaTdQWUluRVE
TEA006 021.srt
TEA006 welcome&overview Kyle Edit02.srt

1. Click on the link below: this is to display that studio creates a unique nr for transcripts
https://studio.proversity.org/container/block-v1:TEA+TEA006+2017+type@vertical+block@c50f3b28193345be9b70c3a88b4742d3
2. Click on EDIT and make sure that a transcript is loaded. heading - Default Timed Transcript
3. Click on advance, note the unique nr that is created for the transcript. Heading - Default Timed Transcript
4. Click on the link below and follow step 3 above to verify the unique nr:
https://studio.proversity.org/container/block-v1:TEA+TEA006+2017+type@vertical+block@b8b791d39df14157bbffb470bd88d447

5. click on the link below: this is to show current issue:
https://studio.proversity.org/container/block-v1:TEA+TEA006+2017+type@vertical+block@8dbc7127d7df4ab385e964b4d4e1e083
6. Click on EDIT and upload a transcript that was saved on your computer. 
7. Click on ADVANCE Note the unique number is displayed as 'Playlist '- Heading - Default Timed Transcript. 
8. Click save and NOTE the text (transcript) next to the video- remember the fir0ts line
9. Click on the link below:
https://studio.proversity.org/container/block-v1:TEA+TEA006+2017+type@vertical+block@1c498da2dd9e41af949a071fe6f1a25e
10. Click on EDIT and upload a transcript that was saved on your computer. Not the same one that was loaded in step 6. 
7. Click on ADVANCE Note the unique number is displayd as 'Playlist '- Heading - Default Timed Transcript. 
8. Click save and note the text (transcript) next to the video
9. click on the link again in step 5.

Results:
The transcript get overwritten by the previous one that is loaded. and has the affect through out module 2 course.

Expected results:
when the user uploads a transcript it should not over wright the other files that were uploaded.

**Comment by nicovanniekerk** [comment]
@mariushuman @renevatium @jagonzalr 

Hi Guys,

I do not think this is an actual bug but a "by design" issue that has crept up due to the incorrect use of studio.

The above steps show that for the linked courses, the transcripts of the videos contained in module 2 all override each other's transcripts, so then you upload a transcript to video two, video one will also now display the same transcript. I am not able to reproduce this in any other place than this courses` module 2.

I believe that the uniqueness constraint in the video to transcript relationship was violated and is now "set in stone", i.e. the same transcript id is kept by the system if you upload a new one, and the same transcript was uploaded to each video or the ids were entered the same.

I did, however, find that when i changed the video url for one of the module 2 videos to that of a module 1 video the transcript updated to that of the module 1transcript,, and now if you upload a new transcript for the module 2 video the same transcript will be displayed on the module 1 video, and the other module 2 videos will be un touched.

**Comment by nicovanniekerk** [comment]
this was an issue with the new MVP platform.

@mariushuman if it has been sorted please close ticket

**Comment by mariushuman** [comment]
@nicovanniekerk the issue was resolved. 
I will close the ticket - Thanks
