### ISSUE TITLE
Learner cannot Unenroll, Unenroll button is not appearing

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#541]
When a user has completed a course and received a certificate, and attempts to Unenroll from the course the 'Unenroll' button does not display. It looks like the button appears behind the 'Option' tab.

url: https://khda.proversity.org

Steps:
1.  Click on the link above and login
2.  If you gave not complete the course, the learner can click on 'Options' and Unenrol from the course
3.  Complete the course to achieve your 'Certificate'
4.  Click on the Hamburger Menu and click Dashboard.
5.  Click on 'Options' to Unenroll

Results:
The learner cannot unenroll

Expected Results
The learner should be able to click On 'Option' and Unenroll from the course.

**Comment by nicovanniekerk** [comment]
@mariushuman this can either be a bug or a by design thing, so yes its a bug that the button is misaligned on the page, we will do some css for that. but here is the actual thing.

If you do a course and finish it and then get the certificate, on all the online sites i have been on ever, you stay enrolled in the course but it moves to an "done" or "archived" list. which i my mind is the right thing to do, cause if you unenroll from the course, there are potential future information you will still need or just some hidden case where you need access again, and also it gives the user the ability to revisit the course at any time to do some refreshing. so let's post this question to the greater team, please draught a pretty poll thingy we can send to everyone. a little survey. especially the learning designers, these guys know learners and how things are meant or how they want it to be, so let's get their take on it.

**Comment by mariushuman** [comment]
@nicovanniekerk , I will close this ticket.

Feedback:
I see that on production, the 'Options' tab is visible, but it contains nothing, so the user cannot Unenroll from a course. 
Although, if the user is still busy with the course, he can unenroll. Should he re-enroll again, his history of the course is loaded, (Bookmarks, questions answered, etc)

**Comment by nicovanniekerk** [comment]
@mariushuman thanks. close it ya, but please keep a reference of this
somewhere to find it when people come shouting because its on staging or
something.
