### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#613]
When changes are being made in django, the user gets a 500 error

Scenario 01
Steps:

1.  Login to django (Staging)
2.  Select user
3.  search for choppies7@hotmail.com
4.  Select the user by ticking it.
5.  Select Delete selected user from 'Action'
6.  Click 'Go'

Results: the user gets an 500 error

Scenario 02

Steps:

1.  Login to django (Staging)
2.  Do a search for ' course enrollments' and click on it.
3.  Do a search for 'cit' and select the course where the user name is 'choppies'
4.  Change the mode of the course to verified.

Results: The user gets a 500 error

Expected results:
The user should be able to changes the settings without getting the error message.

**Comment by mariushuman** [comment]
The following appear in the log file:
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 143, in get_p$    return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/xmodule_django/models.py", line 127, in get_prep_lookup
    _strip_value(value, lookup)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 727, $    return self.get_prep_value(value)
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/xmodule_django/models.py", line 134, in get_prep_value
    assert isinstance(value, self.KEY_CLASS), "%s is not an instance of %s" % (value, self.KEY_CLASS)
AssertionError: course-v1:CIT+demo1+2017_t1 is not an instance of <class 'opaque_keys.edx.keys.CourseKey'>

**Comment by nicovanniekerk** [comment]
Putting this in review due to the follow,
1.  i am about to attempt the next upgrade of edx, will retest this after the upgrade, maybe it gets fixed.
2. For course_enrollments, there is an assertion on the "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/xmodule_django/models.py" file that just causes this action/update/delete to break. this still works if you just comment out the line of code, why? same as above, attempting upgrade and see if that fixes it.
On the delete of the user"choppies7@hotmail" there is a unicode conversion that happens which just breaks, again hope the upgrade fixes it.
Temp fix for this is to comment out line 131
We will revisit this after upgrading

**Comment by nicovanniekerk** [comment]
@mariushuman i do not member if i fixed this or not, can you please check when you have a sec. if it works, just close this.

**Comment by mariushuman** [comment]
Issues fixed, ticket can be closed.
