### ISSUE TITLE
Email info popup display only when in focus

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#665]
When a user register and enters a email address that is already registered in the system, the user should get a popup message saying that the email address belongs to an existing user. 

url: https://khda.proversity.org
All registration spages

Steps1
1.  Click on the link above and select Register
2.  Enter an email address that already exist in the DB
3.  Click in the full name box

Results.
The system does nothing

Expected Results
1.  Click on the link above and select Register
2.  Enter an email address that already exist in the DB
3.  Click in the full name box
4.  Click in the Email box again.

Expected results.
The message that appear should display as soon as the user move out of the email box

**Comment by nicovanniekerk** [comment]
@mariushuman this is not a bug, its a flaw in the design, because EDX.

the validation on names and emails is only done once you click register, the validation that happens when you release focus from a input field is just a "is there something" here check. so we can really fix this. 

But please ensure this is on our list for the new login system tonio is building.
